cabal-version:      3.0
name:               chess
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Tengda Jiang
maintainer:         tdjndv@gmail.com
build-type:         Simple
extra-doc-files:    README.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Chess
    build-depends:
        base ^>=4.20.2.0,
        array
    hs-source-dirs:   src
    default-language: GHC2021

executable chess
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        chess
    hs-source-dirs:   app
    default-language: GHC2021